wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649830545
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.14
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
epsilon_decay_rate:
  desc: null
  value: 393
gamma:
  desc: null
  value: 0.1053580682978636
lr:
  desc: null
  value: 0.19869459784057805
max_episodes:
  desc: null
  value: 1000
max_steps:
  desc: null
  value: 100000
p_end:
  desc: null
  value: 0.1
replay_buffer_size:
  desc: null
  value: 40000
target_freq:
  desc: null
  value: 434
weight_decay:
  desc: null
  value: 0.14667586106653027
