wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1647839051
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.7737719383028897
batch_size:
  desc: null
  value: 32
epsilon:
  desc: null
  value: 0.7886035415003434
gamma:
  desc: null
  value: 0.5964253322215701
max_episodes:
  desc: null
  value: 100
max_steps:
  desc: null
  value: 1000
replay_buffer_size:
  desc: null
  value: 10000
