wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1648000582
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.4447833393443487
batch_size:
  desc: null
  value: 64
decay_rate:
  desc: null
  value: 0.9808620400555428
epsilon:
  desc: null
  value: 0.9251817184201212
gamma:
  desc: null
  value: 0.972971182286298
max_episodes:
  desc: null
  value: 500
max_steps:
  desc: null
  value: 10000
replay_buffer_size:
  desc: null
  value: 10000
