wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1648048964
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.11
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.8180978626027485
batch_size:
  desc: null
  value: 64
decay_rate:
  desc: null
  value: 0.536142201506147
delta:
  desc: null
  value: 2.0607425038520466
epsilon:
  desc: null
  value: 0.3760586899176515
gamma:
  desc: null
  value: 0.7036142078568877
max_episodes:
  desc: null
  value: 1000
max_steps:
  desc: null
  value: 10000
replay_buffer_size:
  desc: null
  value: 10000
