wandb_version: 1

batch_size:
  value: 64
epsilon_decay_rate:
  value: 393
gamma:
  value: 0.1053580682978636
lr:
  value: 0.19869459784057805
max_episodes:
  value: 1000
max_steps:
  value: 100000
p_end:
  value: 0.1
replay_buffer_size:
  value: 40000
target_freq:
  value: 434
weight_decay:
  value: 0.14667586106653027
